### ISSUE TITLE
role hosts - use only hosts_additional_entries without inventory

### ISSUE THREAD

**Issue by muellerbe** [osism/ansible-collection-commons#279]
modify 
https://github.com/osism/ansible-collection-commons/blob/main/roles/hosts/templates/hosts-template.j2
to use only hosts_additional_entries

**Comment by berendt** [comment]
This is already possible by using the ``hosts_use_dns_as_single_source_of_truth`` parameter.

Added missing documentation with fc471aca6473b059d22e73fee53ae0d492c761c3.
