### ISSUE TITLE
network: support creating dummy interfaces and creating link devices

### ISSUE THREAD

**Issue by muellerbe** [osism/ansible-collection-commons#281]
extend role network for creating dummy interfaces and creating link devices

/etc/systemd/network/10-lo-bgp.netdev

[NetDev]
Name=lo-bgp
Kind=dummy

/etc/systemd/network/20-lo-vxlan.netdev

[NetDev]
Name=lo-vxlan
Kind=dummy

ip link add vrrp100 link bond-XX addrgenmode random type macvlan mode bridge

ip link set dev vrrp100 address 00:00:5e:00:01:64

**Comment by muellerbe** [comment]
extend tasks/main with something like
- name: Include dummy interfaces tasks
  ansible.builtin.include_tasks: dummy-interfaces.yml
  when: dummy_interfaces|bool

and work with templates

**Comment by muellerbe** [comment]
https://major.io/2015/10/26/systemd-networkd-and-macvlan-interfaces/

**Comment by berendt** [comment]
Closed by 32d91a6c501a8863d732e4f932b672c3601c8b02
