### ISSUE TITLE
motd spam

### ISSUE THREAD

**Issue by frosty-geek** [osism/ansible-collection-commons#296]
Hi,

is there a reason why we ship a motd in roles/motd/defaults/main.yml?

This clutters the output we get from SSH:

> ------------------------------------------------------------------------------
> * WARNING                                                                    *
> * You are accessing a secured system and your actions will be logged along   *
> * with identifying information. Disconnect immediately if you are not an     *
> * authorized user of this system.                                            *
> ------------------------------------------------------------------------------
> 
> Filesystem      Size  Used Avail Use% Mounted on

or

> ------------------------------------------------------------------------------
> * WARNING                                                                    *
> * You are accessing a secured system and your actions will be logged along   *
> * with identifying information. Disconnect immediately if you are not an     *
> * authorized user of this system.                                            *
> ------------------------------------------------------------------------------
> Linux hostname1 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

IMHO anyone "unauthorized" to connect to the system would disconnect from it due to the above.

regards,
Ralf

**Comment by berendt** [comment]
This was/is the default in the ansible-hardening role. The note is there by default because some security certifications (STIG?) list it as requirement to have it. You can set the parameter to `““`. This was you disable the message.

**Comment by frosty-geek** [comment]
> The operating system must display the Standard Mandatory DoD Notice and Consent Banner before granting local or remote access to the system via a graphical user logon. (V-71859)[¶](https://docs.openstack.org/ansible-hardening/latest/rhel7/auto_controls-all.html#the-operating-system-must-display-the-standard-mandatory-dod-notice-and-consent-banner-before-granting-local-or-remote-access-to-the-system-via-a-graphical-user-logon-v-71859)

Department of Defense probably does not apply to alot of us, but I'm fine if this is the reason why it's done.

**Comment by berendt** [comment]
We extracted the motd tasks from the ansible-hardening role and took the defaults from there. The ansible-hardening role implements all these requirements.

Let's discuss this briefly next week in SCS Team 1 how the others see it. I am open to set this to an empty string by default.
