### ISSUE TITLE
Configuration: add branch to task name

### ISSUE THREAD

**Issue by muellerbe** [osism/ansible-collection-commons#360]
during operating or deployment testing it is necessary to change git branch, so one question, can we create a PR for adding branch name in task names?

e.g.
https://github.com/osism/ansible-collection-commons/blob/main/roles/configuration/tasks/git.yml
old
- name: git - clone configuration repository (ssh / with auth)
new
- name: git - clone configuration repository (ssh / with auth) with branch {{ configuration_git_version }}

**Comment by berendt** [comment]
Nothing speaks against it from my point of view. Feel free.
