### ISSUE TITLE
motd role tries to disable static service

### ISSUE THREAD

**Issue by gndrmnn** [osism/ansible-collection-commons#540]
The ``motd`` role tries to disable the ``motd-news.service`` which seems to be futile, because the service is ``static`` and static services can not be disabled

https://github.com/osism/ansible-collection-commons/blob/main/roles/motd/tasks/configure-Debian.yml#L21

https://bbs.archlinux.org/viewtopic.php?id=147964

**Comment by berendt** [comment]
In the end update-motd should be disabled.
